// Starting sources and listings. Used by `npm run seed` (Supabase) and by the
// in-memory preview store. Listings here stay until the collectors verify
// fresher data; their "last verified" date is the day they were checked by hand.

import { dedupeKey, parseAges } from "./pipeline/normalize";
import type { ListingFields, Source } from "./types";

export const SEED_VERIFIED_AT = "2026-10-01T17:00:00.000Z"; // Oct 1, 2026, 10am in SF

// [url slug, branch name, our neighborhood]
const SFPL_BRANCHES = [
  ["presidio", "Presidio", "laurel-heights"],
  ["golden-gate-valley", "Golden Gate Valley", "cow-hollow"],
  ["richmond", "Richmond", "richmond"],
  ["parkside", "Parkside", "sunset"],
  ["ortega", "Ortega", "sunset"],
  ["sunset", "Sunset", "sunset"],
  ["park", "Park", "haight"],
  ["western-addition", "Western Addition", "western-addition"],
  ["north-beach", "North Beach", "russian-hill"],
  ["noe-valley", "Noe Valley", "noe-valley"],
  ["eureka-valley", "Eureka Valley", "noe-valley"],
  ["mission", "Mission", "mission"],
  ["mission-bay", "Mission Bay", "soma"],
  ["bernal-heights", "Bernal Heights", "bernal-heights"],
  ["potrero", "Potrero", "potrero-hill"],
] as const;

type SeedSource = Omit<
  Source,
  "id" | "created_at" | "last_run_at" | "last_success_at" | "last_error" | "last_count" | "needs_attention"
>;

export const SEED_SOURCES: SeedSource[] = [
  {
    slug: "sfpl-marina",
    name: "SF Public Library — Marina Branch",
    provider: "SFPL Marina",
    url: "https://sfpl.org/locations/marina",
    neighborhood: "marina",
    method: "html",
    trusted: false,
    active: true,
    check_frequency: "daily",
    options: { keywords: ["storytime", "baby", "babies", "toddler", "family", "families"] },
    parser_notes:
      "Branch page lists upcoming events. SFPL's events calendar (sfpl.org/events/calendar) may offer an iCal export: if you find a feed URL, switch method to ics, set url to the feed and options.categories to [\"Babies\",\"Toddlers\",\"Families\"].",
  },
  {
    slug: "sfpl-anza",
    name: "SF Public Library — Anza Branch",
    provider: "SFPL Anza",
    url: "https://sfpl.org/locations/anza",
    neighborhood: "richmond",
    method: "html",
    trusted: false,
    active: true,
    check_frequency: "daily",
    options: { keywords: ["storytime", "baby", "babies", "toddler", "family", "families"] },
    parser_notes: "Same layout as the Marina branch page. See sfpl-marina notes about an ICS feed.",
  },
  // More SF Public Library branches, one source each (same page layout as Marina).
  ...SFPL_BRANCHES.map(([slug, branch, neighborhood]) => ({
    slug: `sfpl-${slug}`,
    name: `SF Public Library — ${branch} Branch`,
    provider: `SFPL ${branch}`,
    url: `https://sfpl.org/locations/${slug}`,
    neighborhood,
    method: "html" as const,
    trusted: false,
    active: true,
    check_frequency: "daily" as const,
    options: { keywords: ["storytime", "baby", "babies", "toddler", "family", "families"] },
    parser_notes: "Branch page lists upcoming events. Same layout as the Marina branch.",
  })),
  {
    slug: "sf-music-together",
    name: "SF Music Together",
    provider: "Music Together",
    url: "https://www.sfmusictogether.com/classes.aspx",
    neighborhood: null,
    method: "html",
    trusted: false,
    active: true,
    check_frequency: "daily",
    options: {},
    parser_notes:
      "One page lists every location (Fort Mason Building C, others) with day, time, price and Full/Waitlist status. Server-rendered ASP.NET page.",
  },
  {
    slug: "jccsf-playdate",
    name: "JCC San Francisco — Playdate",
    provider: "JCCSF",
    url: "https://www.jccsf.org/program/playdate",
    neighborhood: "laurel-heights",
    method: "html",
    trusted: false,
    active: true,
    check_frequency: "weekly",
    options: {},
    parser_notes: "Baby & Me Yoga and open gym. Series dates and prices are on the program page.",
  },
  {
    slug: "kinspace-mama-babe",
    name: "Kinspace — Mama + Babe groups",
    provider: "Kinspace",
    url: "https://kinspacefamily.com/mama-babe",
    neighborhood: "cow-hollow",
    method: "html",
    trusted: false,
    active: true,
    check_frequency: "weekly",
    options: {},
    parser_notes: "Paid 8-week groups grouped by baby's birth month, at 2154 Union St.",
  },
  {
    slug: "sprout-sf",
    name: "Sprout San Francisco — events",
    provider: "Sprout San Francisco",
    url: "https://www.sproutsanfrancisco.com/events",
    neighborhood: null,
    method: "html",
    trusted: false,
    active: false,
    check_frequency: "weekly",
    options: {},
    parser_notes: "URL not yet confirmed — open their site, find the events page, update url, then set active.",
  },
  {
    slug: "jamaroo-kids",
    name: "JAMaROO Kids — Cow Hollow",
    provider: "JAMaROO Kids",
    url: "https://jamarookids.com",
    neighborhood: "cow-hollow",
    method: "manual",
    trusted: false,
    active: true,
    check_frequency: "weekly",
    options: {},
    parser_notes:
      "Classes at 2116 Union St are booked through Care.com, which we don't scrape. Update times by hand from jamarookids.com.",
  },
  {
    slug: "the-pad-studios",
    name: "The Pad Studios",
    provider: "The Pad Studios",
    url: "https://thepadstudios.com",
    neighborhood: "cow-hollow",
    method: "playwright",
    trusted: false,
    active: false,
    check_frequency: "weekly",
    options: { waitFor: "body", settleMs: 3000 },
    parser_notes:
      "Booking moved to Momence (JavaScript calendar). Set url to their public Momence schedule page and activate, or switch to manual.",
  },
  {
    slug: "natural-resources",
    name: "Natural Resources",
    provider: "Natural Resources",
    url: "https://www.naturalresourcesonline.com",
    neighborhood: null,
    method: "manual",
    trusted: false,
    active: true,
    check_frequency: "monthly",
    options: {},
    parser_notes: "Booking system not confirmed. Update by hand.",
  },
  {
    slug: "community-well",
    name: "Community Well",
    provider: "Community Well",
    url: "https://www.communitywell.com",
    neighborhood: null,
    method: "manual",
    trusted: false,
    active: true,
    check_frequency: "monthly",
    options: {},
    parser_notes: "Booking system not confirmed. Update by hand.",
  },
  {
    slug: "outer-village",
    name: "Outer Village",
    provider: "Outer Village",
    url: "https://www.outervillage.org",
    neighborhood: "sunset",
    method: "manual",
    trusted: false,
    active: true,
    check_frequency: "monthly",
    options: {},
    parser_notes: "Booking system not confirmed. Update by hand.",
  },
  {
    slug: "eventbrite-sf-baby",
    name: "Eventbrite — SF baby organisers",
    provider: "Eventbrite",
    url: "https://www.eventbrite.com",
    neighborhood: null,
    method: "api",
    trusted: true,
    active: false,
    check_frequency: "daily",
    options: { kind: "eventbrite", organizerIds: [], keywords: ["baby", "infant", "mom and baby"] },
    parser_notes:
      "Eventbrite's API no longer supports city-wide search. Add organiser IDs of baby-friendly organisers to options.organizerIds, set EVENTBRITE_TOKEN, then activate.",
  },
];

type SeedListing = ListingFields & {
  source_slug: string;
  provider: string;
  last_verified_at: string | null;
  /** Defaults to approved. Pending ones wait in the admin review queue. */
  status?: "approved" | "pending";
  review_note?: string | null;
};

const base: Omit<ListingFields, "name"> = {
  type: null,
  day_of_week: null,
  date: null,
  start_time: null,
  end_time: null,
  series_start: null,
  series_end: null,
  location_name: null,
  address: null,
  neighborhood: null,
  ages_text: null,
  age_min_months: null,
  age_max_months: null,
  is_free: null,
  price: null,
  price_details: null,
  availability: null,
  description: null,
  url: null,
};

export const SEED_LISTINGS: SeedListing[] = [
  {
    ...base,
    source_slug: "sfpl-marina",
    provider: "SFPL Marina",
    name: "Family Storytime",
    type: "storytime",
    day_of_week: 2,
    start_time: "10:30",
    end_time: "11:00",
    location_name: "Marina Branch Library",
    address: "1890 Chestnut St",
    neighborhood: "marina",
    ages_text: "Babies, toddlers and families",
    age_min_months: 0,
    age_max_months: 60,
    is_free: true,
    price: "Free",
    description: "Stories, songs and rhymes for little ones and their grown-ups at the Marina library.",
    url: "https://sfpl.org/locations/marina",
    last_verified_at: SEED_VERIFIED_AT,
  },
  {
    ...base,
    source_slug: "sfpl-marina",
    provider: "SFPL Marina",
    name: "Preschool Storytime",
    type: "storytime",
    day_of_week: 5,
    start_time: "15:00",
    end_time: "15:30",
    location_name: "Marina Branch Library",
    address: "1890 Chestnut St",
    neighborhood: "marina",
    ages_text: "Preschoolers",
    age_min_months: 36,
    age_max_months: 60,
    is_free: true,
    price: "Free",
    description: "An afternoon storytime aimed at preschoolers; younger siblings welcome to tag along.",
    url: "https://sfpl.org/locations/marina",
    last_verified_at: SEED_VERIFIED_AT,
  },
  {
    ...base,
    source_slug: "jccsf-playdate",
    provider: "JCCSF",
    name: "Baby & Me Yoga",
    type: "yoga",
    day_of_week: 3,
    start_time: "10:00",
    end_time: "11:20",
    series_start: "2026-09-09",
    series_end: "2026-12-09",
    location_name: "JCC San Francisco",
    address: "3200 California St",
    neighborhood: "laurel-heights",
    ages_text: "6 weeks to pre-crawling",
    age_min_months: 1,
    age_max_months: 8,
    is_free: false,
    price: "$180",
    price_details: "$180 per 6 weeks (fall series 9/9 to 12/9)",
    description: "Gentle postnatal yoga with your pre-crawling baby on the mat beside you.",
    url: "https://www.jccsf.org/program/playdate",
    last_verified_at: SEED_VERIFIED_AT,
  },
  {
    ...base,
    source_slug: "sf-music-together",
    provider: "Music Together",
    name: "Music Together — Fort Mason",
    type: "music",
    day_of_week: 1,
    start_time: "17:00",
    end_time: "17:45",
    series_start: "2026-10-19",
    series_end: "2026-12-14",
    location_name: "Fort Mason Building C, Room C230",
    address: "2 Marina Blvd",
    neighborhood: "marina",
    ages_text: "Mixed ages 0–5",
    age_min_months: 0,
    age_max_months: 60,
    is_free: false,
    price: "About $273–298",
    price_details: "Fall session Oct 19 to Dec 14",
    availability: "waitlist",
    description: "Mixed-age family music class with singing, instruments and movement. Currently full with a waitlist.",
    url: "https://www.sfmusictogether.com/classes.aspx",
    last_verified_at: SEED_VERIFIED_AT,
  },
  {
    ...base,
    source_slug: "sfpl-anza",
    provider: "SFPL Anza",
    name: "Storytime for Babies",
    type: "storytime",
    day_of_week: 6,
    start_time: "10:30",
    end_time: "11:30",
    location_name: "Anza Branch Library",
    address: "550 37th Ave",
    neighborhood: "richmond",
    ages_text: "Babies",
    age_min_months: 0,
    age_max_months: 18,
    is_free: true,
    price: "Free",
    description: "A Saturday-morning storytime for babies with board books, bounces and songs.",
    url: "https://sfpl.org/locations/anza",
    last_verified_at: SEED_VERIFIED_AT,
  },
  // Providers whose times aren't confirmed yet: shown with "Check times".
  ...(
    [
      ["jamaroo-kids", "JAMaROO Kids", "JAMaROO Kids music & movement", "music", "cow-hollow", "2116 Union St", "https://jamarookids.com", "Music, movement and storytime classes for babies and toddlers on Union Street."],
      ["sprout-sf", "Sprout San Francisco", "Sprout San Francisco events", null, null, null, "https://www.sproutsanfrancisco.com", "Parenting classes and baby events; check their calendar for what's on."],
      ["the-pad-studios", "The Pad Studios", "The Pad Studios mom & baby classes", null, "cow-hollow", "1694 Union St", "https://thepadstudios.com", "Fitness studio on Union Street; check their schedule for classes you can bring baby to."],
      ["kinspace-mama-babe", "Kinspace", "Kinspace Mama + Babe groups", "support", "cow-hollow", "2154 Union St", "https://kinspacefamily.com/mama-babe", "Paid 8-week new-mom groups, grouped by baby's birth month."],
      ["natural-resources", "Natural Resources", "Natural Resources classes", null, null, null, "https://www.naturalresourcesonline.com", "Pregnancy and new-parent classes; check their site for current times."],
      ["community-well", "Community Well", "Community Well classes", null, null, null, "https://www.communitywell.com", "Wellness classes for new parents; check their site for current times."],
      ["outer-village", "Outer Village", "Outer Village gatherings", null, "sunset", null, "https://www.outervillage.org", "Community space for families; check their site for current times."],
      ["sf-music-together", "Music Together", "Music Together — other neighborhoods", "music", null, null, "https://www.sfmusictogether.com/classes.aspx", "Family music classes at several SF locations; check their page for times near you."],
    ] as const
  ).map(([source_slug, provider, name, type, neighborhood, address, url, description]) => ({
    ...base,
    source_slug,
    provider,
    name,
    type,
    neighborhood,
    address,
    url,
    description,
    is_free: source_slug === "kinspace-mama-babe" ? false : null,
    price: source_slug === "kinspace-mama-babe" ? "Paid" : null,
    last_verified_at: null,
  })),
  // Found on sfpl.org branch pages via web search on Oct 1, 2026. Waiting in the
  // review queue: confirm each on sfpl.org, then approve.
  ...(
    [
      ["presidio", "Presidio", "Storytime for Babies", 4, "10:15", "10:45", "3150 Sacramento St", "laurel-heights", "Babies"],
      ["noe-valley", "Noe Valley", "Storytime for Babies", 4, "10:15", "10:45", "451 Jersey St", "noe-valley", "Babies"],
      ["parkside", "Parkside", "Storytime for Babies", 4, "10:30", "11:15", null, "sunset", "Babies"],
      ["mission-bay", "Mission Bay", "Storytime for Babies", 4, "10:30", "11:15", null, "soma", "Babies"],
      ["park", "Park", "Storytime for Babies", 6, "11:00", "12:00", "1833 Page St", "haight", "Babies"],
      ["richmond", "Richmond", "Storytime for Babies", 1, "11:00", "12:00", null, "richmond", "Babies"],
      ["north-beach", "North Beach", "Storytime for Babies (English & Español)", 2, "10:15", "10:45", "850 Columbus Ave", "russian-hill", "Babies"],
      ["golden-gate-valley", "Golden Gate Valley", "Storytime for Families", 5, "13:15", "13:45", "1801 Green St", "cow-hollow", "Babies, toddlers and preschoolers"],
      ["western-addition", "Western Addition", "Storytime for Families", 1, "10:15", "10:45", "1550 Scott St", "western-addition", "Babies, toddlers and preschoolers"],
      ["western-addition", "Western Addition", "Storytime for Toddlers", 2, "11:00", "11:30", "1550 Scott St", "western-addition", "16 months to 2 years"],
      ["western-addition", "Western Addition", "Storytime for Babies", 2, "11:45", "12:15", "1550 Scott St", "western-addition", "Babies"],
      ["eureka-valley", "Eureka Valley", "Storytime for Babies", 3, "11:00", "11:30", "1 Jose Sarria Ct", "noe-valley", "Babies"],
    ] as const
  ).map(([slug, branch, name, day, start, end, address, neighborhood, ages]) => {
    const parsed = parseAges(ages);
    return {
      ...base,
      source_slug: `sfpl-${slug}`,
      provider: `SFPL ${branch}`,
      name,
      type: "storytime" as const,
      day_of_week: day,
      start_time: start,
      end_time: end,
      location_name: `${branch} Branch Library`,
      address,
      neighborhood,
      ages_text: ages,
      age_min_months: parsed.min,
      age_max_months: parsed.max,
      is_free: true,
      price: "Free",
      description: name.startsWith("Storytime for Babies")
        ? "Songs, rhymes and board books for babies and their grown-ups at the library."
        : name.startsWith("Storytime for Toddlers")
          ? "Books, songs and movement for toddlers and their grown-ups at the library."
          : "Stories and songs for little ones and their grown-ups at the library.",
      url: `https://sfpl.org/locations/${slug}`,
      last_verified_at: null,
      status: "pending" as const,
      review_note: "Found on sfpl.org via web search, Oct 1 2026. Confirm the day and time on the branch page, then approve.",
    };
  }),
  // Branches where we only found older schedules: shown with "Check times".
  ...(
    [
      ["bernal-heights", "Bernal Heights", "500 Cortland Ave", "bernal-heights"],
      ["ortega", "Ortega", "3223 Ortega St", "sunset"],
      ["sunset", "Sunset", "1305 18th Ave", "sunset"],
      ["potrero", "Potrero", "1616 20th St", "potrero-hill"],
      ["mission", "Mission", null, "mission"],
    ] as const
  ).map(([slug, branch, address, neighborhood]) => ({
    ...base,
    source_slug: `sfpl-${slug}`,
    provider: `SFPL ${branch}`,
    name: `${branch} library storytimes`,
    type: "storytime" as const,
    location_name: `${branch} Branch Library`,
    address,
    neighborhood,
    is_free: true,
    price: "Free",
    description: "Free weekly storytimes for babies, toddlers and families. Check the branch page for this week's times.",
    url: `https://sfpl.org/locations/${slug}`,
    last_verified_at: null,
  })),
];

export function seedDedupeKey(l: SeedListing): string {
  return dedupeKey(l.provider, l);
}
